### ISSUE TITLE
bulk execute returns undefined

### ISSUE THREAD

**Issue by whisper3d** [ARSevo/ars-dataaccess#13]
bulk execute does not returns status information. basically bulk.execute returns a json response simular to the response below
{
  "ok": 1,
  "writeErrors": [],
  "writeConcernErrors": [],
  "insertedIds": [],
  "nInserted": 0,
  "nUpserted": 1,
  "nMatched": 1,
  "nModified": 1,
  "nRemoved": 0,
  "upserted": [
    {
      "index": 1,
      "_id": "xxxxxxxx"
    }
  ]
}

response should be returned in order to detect if the process is successfull.

**Comment by Volem** [comment]
#14
